import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecommerce Mockup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>

        <p>Get started</p>
      </main>

      <footer>Impressum</footer>
    </div>
  );
}
